### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cgarciae** [google-deepmind/optax#3]
Hey, I am a user of optix, it seems optax is going to be the future of the library but I don't see any documentation. Is it too early to use this library?

**Comment by KristianHolsheimer** [comment]
I just wanted to chime in and say that this would be nice to have. I'm working on a project that used to reference some optix functions through intersphinx.. now I don't know where to point it to.

**Comment by mtthss** [comment]
Hi, thanks for reaching out. 

Yes I can confirm that 'optax' is the supported solution going forward. It is already widely used internally at DeepMind and I encourage you to also use 'optax' rather than 'optix', as the latter will be deprecated soon. 

We will be adding more public documentation for 'optax' in the coming weeks.

**Comment by bionicles** [comment]
switched. looks good

**Comment by mtthss** [comment]
We now have documentation on read the docs!
https://optax.readthedocs.io/en/latest/

**Comment by KristianHolsheimer** [comment]
Thanks @mtthss 

It's so nice to walk through the API without being distracted by the code itself. (I just just saw `periodic-update` for the first time, awesome!)

One minor thing.. Some of the sections aren't showing up in the correct hierarchy in sidebar. For instance, "[Apply Updates](https://optax.readthedocs.io/en/latest/api.html#apply-updates)" is listed as a subsubsection (under its predecessor item).

I changed some `----` sections to `====` in #79
