### ISSUE TITLE
Second-order optimizers in optax

### ISSUE THREAD

**Issue by nalzok** [google-deepmind/optax#546]
I want to implement a second-order optimizer (in the sense that it uses curvature information) called [SketchySGD](https://arxiv.org/abs/2211.08597) in optax. One problem is that these methods generally require calculating Hessian-vector products, which optax helpfully supports with [`optax.hvp`](https://optax.readthedocs.io/en/latest/api.html#hvp), whose first argument is the `loss` function. However, I cannot access it in `update_fn` with the default signature `update_fn(updates, state, params=None)`.

Do you think it's a good idea to change the signature to `update_fn(updates, state, params=None, loss_fn=None)`?

**Comment by fabianp** [comment]
I believe you need to return a `GradientTransformationExtraArgs` instead of a `GradientTransformation`, see for example the SAM example (https://github.com/google-deepmind/optax/blob/main/optax/contrib/sam.py). This one implements a `grad_fn` in the update method, while in your case it would be a `loss`, but otherwise the signature should be similar. hope that helps!
