### ISSUE TITLE
Jaxopt vs Optax

### ISSUE THREAD

**Issue by pushkar5586** [google-deepmind/optax#959]
What is the difference between Jaxopt vs Optax? When should we use one instead of the other?

**Comment by soraros** [comment]
We are in the process of merging JAXopt into [Optax](https://github.com/google-deepmind/optax). Because of this, JAXopt is now in maintenance mode and we will not be implementing new features [^1]

[^1]: [](https://github.com/google/jaxopt?tab=readme-ov-file#%EF%B8%8F-we-are-in-the-process-of-merging-jaxopt-into-optax-because-of-this-jaxopt-is-now-in-maintenance-mode-and-we-will-not-be-implementing-new-features-%EF%B8%8F)

**Comment by vroulet** [comment]
Optax is a library to compose gradient transformations. It is tailored for flexible design of deep learning optimization algorithms. 
Jaxopt was designed to implement classical (often non-stochastic) optimization solvers (like LBFGS) that could be differentiated through/vmapped etc...
We are in the process of merging the main utilities present in jaxopt. For example projections from jaxopt have been ported to optax. A simple linesearch is also available and we plan to port lbfgs in the close future.
If there are some functionalities of jaxopt that you'd like to be ported to optax in particular, please let us know.

**Comment by pushkar5586** [comment]
Thanks.
